### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by yuntaowu2000** [yuntaowu2000/CPEN321-Quizzical#7]
Through testing for frontend and backend. Follow the instructions in M9

**Comment by ihsan314** [comment]
Module 9 instructions:
### PART 1
A 1-page status update that includes:
1. A high-level description of the progress since the previous milestone (M8).
2. The plans until the next milestone (M10).
3. Major decisions and changes in the scope of the project (from the requirements and
design document submitted when the groups were formed).
4. The contributions of individual team members to the work done so far.

### PART 2
For this milestone, you will perform **a systematic testing of your project**. You will perform:
1. Automated unit and integration testing for **your** back-end.
2. Automated UI testing for your frond-end.
3. Automated or manual testing for two of **your** non-functional requirements from M3.
4. Manual customer acceptance testing for the app of **your partner team**.

Prepare and submit the following artefacts:
1. For the automated back-end testing [40 points]
• A table summarizing the number of back-end tests per the tested modules and the number of integration tests, as specified in M7 [5 points]
• A screenshot with success/fail condition of each test specified in M7 [10 points]
NOTE: Some tests may still fail at this point, but they will need to pass by M10
• A statement- and method-level coverage report for tests of each of the two modules under test. Make sure you mock all modules besides the one under test [15 points]
• A statement- and method-level coverage report for each integration test separately and all integration tests together [10 points]
Be prepared to run the tests during your meeting with the TA
2. For the automated front-end UI testing [30 points]
• A list of tests you created, with one paragraph describing how you encoded success/failure criteria for each UI test (test oracle) and 2-3 example screenshots [15 points]
• A log of the automated execution of these tests on the device, including their pass/fail status [15 points]
Note: Some tests may still fail at this point, but they will need to pass by M10
Be prepared to run the tests during your meeting with the TA
3. For testing of non-functional requirements [15 points]
• For each non-functional requirements identified in M7, show the log with your verification results. Explain in 1-2 sentences how you verified each requirement.
4. For manual customer acceptance testing for the app of **your partner team** [15 points]
• Meet with your customer team (online) and test their app. Ask them to test yours
• Report one major fault you found in your **partner’s team app**. The report should contain the buggy execution scenario (sequence of events, with screenshots) and the description of the fault [10 points]
• Yes, you will find some major fault – there is no app without faults 2 weeks before the final deadline
• If you report that you cannot find any major fault and then your TA does, you will lose marks. If the TA does not find any major issues either, you will be given the full mark.
• Report one major fault that your peer-team found **in your app**. Provide a short description, no screenshots are needed [5 points]
• If your peer team did not find any major faults in your code, ask your teammates working on the back-end to test the app. Report the identified faults.
• If you report that neither your peer team nor your own team member can find major faults in your app and then your TA does, you both will lose marks. If the TA does not find any faults in your app, you will be given the full mark.
Be prepared to share your screen and run the test and/or show your code during your meeting with the TA!
